### ISSUE TITLE
Bug: Same place name sometimes shown

### ISSUE THREAD

**Issue by gpmcadam** [bothness/ons-geo-game#1]
When offering multiple choice answers, sometimes the same place is listed twice. I assume the random alternatives are not excluding the right answer.

Would have provided a PR but only the compiled code is checked in.

**Comment by bothness** [comment]
Hi @gpmcadam. I hadn't noticed your message. This bug was due to duplicates in the array of place names returned by the API. So two different array items could in fact be the same. This has now been resolved.
